### ISSUE TITLE
Latest version v1.4.2 shows blank screen

### ISSUE THREAD

**Issue by roycornelissen** [riezebosch/gitviz#4]
Hi, I installed v1.4.2. on my M2 Mac and when I start it in my Git repo, it launches the browser, but the output remains blank. There are no errors in the terminal or anything so it's hard to see what is going wrong. So I downloaded and installed v1.4.1, which works like a charm. So there seems to be some regression, at least on my M2 processor :)

**Comment by riezebosch** [comment]
should be fixed: https://github.com/riezebosch/gitviz/releases/tag/v1.4.3

**Comment by roycornelissen** [comment]
Indeed it is 👍  Thanks!!!
